const HERO='data:image/webp;base64,'+(window.HERO_PARTS||[]).join('');document.documentElement.style.setProperty('--hero',`url("${HERO}")`);
const metrics=[['Whole Turkeys Defeated','1','Data verified by absolutely no one.'],['Estimated Calories','Classified','Released only on a need-to-feed basis.'],['Bites Per Minute','47','Peak performance occurred during the breast-meat split.'],['Turkey Coverage','100%','Face, shirt, and surrounding airspace.'],['Leftovers Remaining','0%','Investigators found only bones and questions.'],['Nap Probability','99.9%','The remaining 0.1% is gravy momentum.'],['Gravy Efficiency','Elite','Minimal spillage. Maximum tactical coverage.'],['Shirt Survival Rate','0%','The hoodie gave everything for the mission.']];
const awards=[['WB','The Whole Bird Award','Completed one full turkey without hesitation.'],['ZL','Zero Leftovers Club','Nothing remained except bones and questions.'],['GS','The Gravy Standard','Maintained peak sauce performance throughout the meal.'],['SS','Shirt Sacrifice Medal','The hoodie gave everything for the mission.'],['MVP','Thanksgiving MVP','Most Valuable Predator.']];
const news=[['Breaking','Local Costco Places Tanner on Turkey Watchlist','Warehouse staff have initiated a three-bird minimum buffer.'],['Exclusive','Scientists Confirm Tanner Has a Second Stomach','The research team has requested additional gravy funding.'],['Report','Thanksgiving Dinner Ends Seven Minutes After Tanner Arrives','Family members describe the scene as efficient but emotionally complex.'],['Developing','National Turkey Association Declines to Comment','A spokesperson slowly backed away from the microphone.']];
const products=[
{id:1,name:'Tanner Turkey Devourer Hoodie',price:54.99,category:'Apparel',type:'hoodie',colors:['#203127','#111','#d86a18'],desc:'Dark forest-green heavyweight hoodie with a small embroidered turkey crest and a large ZERO LEFTOVERS back graphic.',badge:'Tanner’s Pick'},
{id:2,name:'Whole Bird Vintage Tee',price:32.99,category:'Apparel',type:'tee',colors:['#eee5d2','#111','#8f4f22'],desc:'Premium cream oversized tee with a distressed Tanner turkey print and ONE BIRD MINIMUM campaign mark.',badge:'Limited Edition'},
{id:3,name:'Devourer Division Trucker Hat',price:27.99,category:'Accessories',type:'hat',colors:['#111','#e76110','#203127'],desc:'Black and burnt-orange trucker hat with embroidered turkey emblem and EST. THANKSGIVING side detail.',badge:'Tanner’s Pick'},
{id:4,name:'Official Turkey Bib',price:19.99,category:'Accessories',type:'bib',colors:['#eee8dc','#111'],desc:'Premium adult bib with PREPARE THE BIRD printed across food-resistant performance fabric.',badge:'Not Edible'},
{id:5,name:'Emergency Gravy Flask',price:18.99,category:'Accessories',type:'flask',colors:['#a9aaa5','#111'],desc:'Brushed metal emergency flask labeled BREAK OPEN IN CASE OF DRY TURKEY.',badge:'Low Stock'},
{id:6,name:'Turkey Destroyer Mug',price:16.99,category:'Accessories',type:'mug',colors:['#f4efe6','#111','#e76110'],desc:'Oversized ceramic mug featuring the official Tanner Turkey Devourer crest.',badge:'Tanner’s Pick'},
{id:7,name:'Tanner Action Figure',price:44.99,category:'Collectibles',type:'figure',colors:['#203127','#e76110'],desc:'Collector packaging with removable turkey, gravy bottle, and destroyed hoodie accessories.',badge:'Limited Edition'},
{id:8,name:'Thanksgiving Survival Kit',price:74.99,category:'Limited Edition',type:'kit',colors:['#1a1d19','#e76110'],desc:'Official bib, gravy flask, Devourer napkins, stretch waistband, warning sign, and emergency dessert fork.',badge:'Limited Edition'},
{id:9,name:'Signed Turkey Bone',price:999.99,category:'Collectibles',type:'bone',colors:['#eee0c3','#c69a45'],desc:'One-of-one signed turkey bone in a luxury glass collector case with a fictional certificate of authenticity.',badge:'One of One'},
{id:10,name:'Zero Leftovers Varsity Jacket',price:129.99,category:'Apparel',type:'jacket',colors:['#111','#eee5d2','#203127'],desc:'Premium black and cream varsity jacket with turkey patch and large embroidered TANNER TURKEY DEVOURER back graphic.',badge:'Limited Edition'}];
const reviews=[['He finished Thanksgiving before we finished saying grace.','Grandma'],['We ordered three turkeys. We still went hungry.','Uncle Bob'],['I looked away for seven seconds.','Eyewitness'],['Our poultry department has been warned.','Local Grocery Store'],['The hoodie survived. Barely.','Laundry Technician']];
const timeline=[['Age 5','First chicken nugget.'],['Age 10','Discovered Thanksgiving.'],['Age 18','Completed his first rotisserie chicken.'],['Today','The whole turkey incident.'],['Next','The buffet prepares for impact.']];
const faqs=[['Is this a real store?','No. The store and products are a fictional parody experience.'],['Did Tanner really eat the entire turkey?','The evidence speaks for itself.'],['Why is there turkey on his hoodie?','Collateral damage.'],['Can I challenge Tanner?','Bring two turkeys and a written apology.'],['Are the products edible?','No. Tanner asked the same thing.'],['Does the cart accept real payments?','No. The checkout is fictional and must never request payment information.']];
let cart=[],activeProduct=null;
function productSVG(p,alt=false){const c=p.colors[0],a=p.colors[1]||'#e76110',label=alt?'ZERO LEFTOVERS':'TTD';const g=`<defs><linearGradient id="g${p.id}${alt}" x1="0" x2="1"><stop stop-color="${c}"/><stop offset="1" stop-color="${a}"/></linearGradient></defs>`;const t=`<text x="150" y="190" fill="${alt?'#e76110':'#f4eddf'}" text-anchor="middle" font-family="Arial" font-weight="900" font-size="${alt?18:28}">${label}</text>`;let s='';if(p.type==='hoodie'||p.type==='jacket')s=`<path d="M80 70L118 45 150 70 182 45 220 70 250 115 220 145 205 128 215 270 85 270 95 128 80 145 50 115Z" fill="url(#g${p.id}${alt})"/>${t}`;else if(p.type==='tee')s=`<path d="M70 80L115 45Q150 70 185 45L230 80 210 125 190 112 205 275 95 275 110 112 90 125Z" fill="url(#g${p.id}${alt})"/>${t}`;else if(p.type==='hat')s=`<path d="M65 155Q75 65 150 65Q225 65 235 155Z" fill="url(#g${p.id}${alt})"/><path d="M80 155Q185 140 275 180Q210 205 130 188Z" fill="${a}"/>${t.replace('y="190"','y="140"')}`;else if(p.type==='bib')s=`<path d="M105 55Q150 30 195 55L210 105 235 265 65 265 90 105Z" fill="url(#g${p.id}${alt})"/><circle cx="150" cy="78" r="28" fill="#efe8db"/>${t}`;else if(p.type==='flask')s=`<rect x="88" y="65" width="124" height="210" rx="26" fill="url(#g${p.id}${alt})"/><rect x="118" y="42" width="64" height="32" rx="8" fill="#333"/>${t}`;else if(p.type==='mug')s=`<rect x="65" y="80" width="150" height="170" rx="18" fill="url(#g${p.id}${alt})"/><path d="M215 115Q275 110 270 175Q266 235 215 220" fill="none" stroke="${a}" stroke-width="25"/>${t}`;else if(p.type==='figure')s=`<rect x="55" y="25" width="190" height="260" rx="18" fill="#161916" stroke="#e76110" stroke-width="7"/><circle cx="150" cy="95" r="38" fill="#c7835a"/><path d="M105 135Q150 115 195 135L210 245 90 245Z" fill="${c}"/><ellipse cx="185" cy="185" rx="42" ry="27" fill="#9a5a24"/>`;else if(p.type==='kit')s=`<rect x="45" y="60" width="210" height="185" rx="18" fill="url(#g${p.id}${alt})"/><rect x="115" y="38" width="70" height="30" rx="10" fill="none" stroke="#e76110" stroke-width="10"/>${t}`;else s=`<rect x="45" y="35" width="210" height="240" rx="15" fill="rgba(220,235,230,.25)" stroke="#c69a45" stroke-width="6"/><path d="M90 190Q130 135 170 185Q200 215 225 170" fill="none" stroke="#e7d4ac" stroke-width="22" stroke-linecap="round"/><circle cx="82" cy="198" r="18" fill="#e7d4ac"/><circle cx="230" cy="164" r="18" fill="#e7d4ac"/>`;return `<svg viewBox="0 0 300 320">${g}${s}</svg>`}
function renderProducts(filter='All'){const list=filter==='All'?products:products.filter(p=>p.category===filter||p.badge===filter);productGrid.innerHTML=list.map(p=>`<article class="product-card reveal"><div class="product-visual"><div class="badges"><span class="badge ${p.badge.includes('Tanner')?'orange':''}">${p.badge}</span></div><button class="wishlist" onclick="toggleWish(this,event)">♡</button>${productSVG(p)}</div><div class="product-info"><h3 class="product-name">${p.name}</h3><div class="rating">★★★★★ 4.9</div><div class="price">$${p.price.toFixed(2)}</div><div class="swatches">${p.colors.map(c=>`<span class="swatch" style="background:${c}"></span>`).join('')}</div><div class="product-actions"><button class="add" onclick="addToCart(${p.id})">Add to cart</button><button class="quick" onclick="openQuick(${p.id})">Quick view</button></div></div></article>`).join('');observe()}
function addToCart(id){const p=products.find(x=>x.id===id),e=cart.find(x=>x.id===id);e?e.qty++:cart.push({...p,qty:1,size:'L'});updateCart();openCart();showToast('Added. Protect it from Tanner.')}
function updateCart(){cartCount.textContent=cart.reduce((s,x)=>s+x.qty,0);cartItems.innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div class="cart-thumb">${productSVG(x)}</div><div><h4>${x.name}</h4><small>Size: ${x.size}</small><div class="qty"><button onclick="changeQty(${x.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${x.id},1)">+</button></div></div><strong>$${(x.price*x.qty).toFixed(2)}</strong></div>`).join(''):'<p style="text-align:center;color:#655f55;margin-top:70px">Your cart is empty. Tanner may have reached it first.</p>';subtotal.textContent='$'+cart.reduce((s,x)=>s+x.price*x.qty,0).toFixed(2);inventoryNote.textContent=['Only 3 left. Tanner found the warehouse.','Low stock. Protect the remaining units.','Tanner’s Pick.','Not edible. We had to clarify.'][Math.floor(Math.random()*4)]}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);updateCart()}
function openCart(){cartDrawer.classList.add('open');document.body.classList.add('no-scroll')}function closeCart(){cartDrawer.classList.remove('open');document.body.classList.remove('no-scroll')}
function openQuick(id){activeProduct=products.find(x=>x.id===id);quickVisual.innerHTML=productSVG(activeProduct,true);quickName.textContent=activeProduct.name;quickDesc.textContent=activeProduct.desc;quickPrice.textContent='$'+activeProduct.price.toFixed(2);quickModal.classList.add('open');document.body.classList.add('no-scroll')}
function closeModal(x){x.classList.remove('open');document.body.classList.remove('no-scroll')}function toggleWish(b,e){e.stopPropagation();b.textContent=b.textContent==='♡'?'♥':'♡';showToast(b.textContent==='♥'?'Saved to imaginary wishlist.':'Removed from imaginary wishlist.')}
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),2500)}
function turkeyMode(){showToast('TURKEY MODE ACTIVATED');for(let i=0;i<55;i++){const f=document.createElement('div');f.className='feather';f.style.left=Math.random()*100+'vw';f.style.setProperty('--drift',(Math.random()*260-130)+'px');f.style.animationDuration=(2.7+Math.random()*2.4)+'s';document.body.appendChild(f);setTimeout(()=>f.remove(),6000)}}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.1});document.querySelectorAll('.reveal:not(.visible)').forEach(x=>io.observe(x))}
