metricGrid.innerHTML=metrics.map(m=>`<article class="metric-card reveal"><small>${m[0]}</small><strong>${m[1]}</strong><span class="tooltip">${m[2]}</span></article>`).join('');
awardsGrid.innerHTML=awards.map(a=>`<article class="award reveal"><div class="medal">${a[0]}</div><h3>${a[1]}</h3><p>${a[2]}</p></article>`).join('');
newsGrid.innerHTML=news.map(n=>`<article class="news-card reveal"><div><span class="news-label">${n[0]}</span><h3>${n[1]}</h3></div><p>${n[2]}</p></article>`).join('');
reviewTrack.innerHTML=reviews.map(r=>`<article class="review"><div class="stars">★★★★★</div><blockquote>“${r[0]}”</blockquote><cite>— ${r[1]}</cite></article>`).join('');
timelineList.innerHTML=timeline.map(t=>`<article class="timeline-item reveal"><div class="timeline-age">${t[0]}</div><div class="timeline-copy"><strong>${t[1]}</strong><p>${t[0]==='Next'?'Venue staff have begun reinforcing the dessert table.':'Historical appetite milestone.'}</p></div></article>`).join('');
faqList.innerHTML=faqs.map(f=>`<div class="faq-item"><button class="faq-q" onclick="this.parentElement.classList.toggle('open')"><span>${f[0]}</span><span>+</span></button><div class="faq-a">${f[1]}</div></div>`).join('');
renderProducts();galleryMerch.innerHTML=productSVG(products[0]);
window.addEventListener('load',()=>{setTimeout(()=>loader.classList.add('hide'),400);observe()});window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',scrollY>25);backTop.classList.toggle('show',scrollY>650)});
backTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});cartButton.onclick=openCart;document.getElementById('closeCartButton').onclick=closeCart;document.querySelector('.drawer-backdrop').onclick=closeCart;mobileToggle.onclick=()=>mobileMenu.classList.toggle('open');document.querySelectorAll('#mobileMenu a').forEach(a=>a.onclick=()=>mobileMenu.classList.remove('open'));document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter)});
document.querySelector('#quickModal .modal-close').onclick=()=>closeModal(quickModal);quickAdd.onclick=()=>{if(activeProduct){closeModal(quickModal);addToCart(activeProduct.id)}};checkoutButton.onclick=()=>{closeCart();checkoutModal.classList.add('open')};returnFeast.onclick=()=>closeModal(checkoutModal);inventoryCancel.onclick=()=>{document.querySelector('#checkoutModal h2').innerHTML='Order Cancelled.<br>Tanner Ate the Inventory.';document.querySelector('#checkoutModal p').textContent='No payment was collected. The remaining evidence is being reviewed.'};signupForm.onsubmit=e=>{e.preventDefault();e.target.reset();signupMessage.style.display='block'};document.querySelectorAll('.gallery-item').forEach(x=>x.onclick=()=>{lightbox.classList.add('open');document.body.classList.add('no-scroll')});document.querySelector('#lightbox .modal-close').onclick=()=>closeModal(lightbox);
let clicks=0,clickTimer;logo.onclick=e=>{clicks++;clearTimeout(clickTimer);clickTimer=setTimeout(()=>clicks=0,1800);if(clicks>=5){e.preventDefault();clicks=0;turkeyMode()}};secretTurkey.onclick=e=>{e.preventDefault();turkeyMode()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();document.querySelectorAll('.modal.open').forEach(closeModal)}})